"""
Konfiguracja wymiarów, kolorów i stałych dla aplikacji Nixie Clock Control
Zmień wartości tutaj żeby dostosować wygląd aplikacji
"""

# ===== WYMIARY OKNA =====
WINDOW_WIDTH = 700
WINDOW_HEIGHT = 1150

# ===== WYMIARY KONTROLEK =====
INPUT_HEIGHT = 38
SLIDER_HEIGHT = 6
CONSOLE_HEIGHT = 150

# Szerokości
TIME_EDIT_WIDTH = 120
TIME_EDIT_FULL_WIDTH = 180
BUTTON_WIDTH = 100
PORT_COMBO_MIN_WIDTH = 200

# ===== ODSTĘPY =====
SECTION_SPACING = 16
ELEMENT_SPACING = 12
TIME_FIELDS_SPACING = 20

# Marginesy
WINDOW_MARGIN = 24
GROUPBOX_PADDING = "20px 14px 14px 14px"
GROUPBOX_MARGIN_TOP = 18
GROUPBOX_TITLE_LEFT = "12px"

# ===== KOLORY =====
COLOR_BACKGROUND = "#1e1e1e"
COLOR_PRIMARY = "#0a84ff"
COLOR_PRIMARY_HOVER = "#0066cc"
COLOR_PRIMARY_PRESSED = "#004999"

COLOR_SUCCESS = "#30d158"
COLOR_WARNING = "#ff9500"
COLOR_DANGER = "#ff3b30"

COLOR_TEXT_PRIMARY = "#ffffff"
COLOR_TEXT_SECONDARY = "rgba(255, 255, 255, 0.8)"
COLOR_TEXT_DISABLED = "rgba(255, 255, 255, 0.3)"
COLOR_TEXT_MUTED = "rgba(255, 255, 255, 0.5)"

COLOR_GROUPBOX_BG = "rgba(50, 50, 50, 0.5)"
COLOR_INPUT_BG = "rgba(0, 0, 0, 0.3)"
COLOR_CONSOLE_BG = "rgba(0, 0, 0, 0.3)"

COLOR_BORDER = "rgba(255, 255, 255, 0.1)"
COLOR_BORDER_FOCUS = "rgba(255, 255, 255, 0.15)"

# ===== CZCIONKI =====
FONT_FAMILY = "-apple-system, BlinkMacSystemFont, 'SF Pro Display', 'Helvetica Neue', sans-serif"
FONT_MONO = "'SF Mono', 'Monaco', 'Consolas', monospace"

FONT_SIZE_HEADER = "22px"
FONT_SIZE_SUBTITLE = "13px"
FONT_SIZE_NORMAL = "13px"
FONT_SIZE_SMALL = "12px"
FONT_SIZE_TINY = "11px"

# ===== ZAOKRĄGLENIA =====
BORDER_RADIUS_LARGE = "10px"
BORDER_RADIUS_MEDIUM = "8px"
BORDER_RADIUS_SMALL = "4px"

# ===== WARTOŚCI DOMYŚLNE =====
DEFAULT_BRIGHTNESS = 100
DEFAULT_NIGHT_BRIGHTNESS = 20
DEFAULT_DIM_START = "22:00"
DEFAULT_DIM_END = "08:00"
DEFAULT_OFF_TIME = "23:00"
DEFAULT_ON_TIME = "07:00"

# ===== SERIAL =====
DEFAULT_BAUD_RATE = 9600
PORT_REFRESH_INTERVAL = 2000
